import '../style/Story.scss'

export default function Story() {
    return (
        <div className="story">
            <h1>Harry Potter és a bölcsek köve</h1>

            <p>Harry Potter árva kisfiú, szülei meghaltak egyéves korában. Nagynénje családjánál nevelkedik, akik utálatosan viselkednek vele. A 11. születésnapján megtudja egy óriástól, kinek varázspálcája az esernyőjében van, hogy varázsló, és felvételt nyert a Roxfort Boszorkány- és Varázslóképző Szakiskolába. A szülei is varázslók voltak, de Voldemort, a gonosz varázsló, megölte őket. Amikor Harryt akarta meggyilkolni, a varázslat visszacsapott és végletesen meggyengítette Voldemort-t. Harry homlokán egy villám alakú sebhely maradt, a varázslóvilág csodaként tekintett rá, amiről ő nem tudott semmit.

            Az iskolában fokozatosan megismeri a számára teljesen új varázsvilágot, és szert tesz két jó barátra, Ronald bilius Weasleyre és Hermione Jean Grangerre. Megtanul kviddicsezni, így az elmúlt száz év legfiatalabb fogója lesz belőle ,ahogy az apjából is az lett fiatal korában. A tanév során kiderül, hogy Voldemort nagyúr, aki tíz éve minden hatalmát elvesztette, megpróbálja megszerezni a bölcsek kövét, hogy így újra testet ölthessen, és visszatérhessen a hatalomba. Harryék szinte biztosak benne, hogy ebben őt Perselus Piton professzor, Harry legellenszenvesebb tanára (bájitaltan) segíti. Év végén Harryék elhatározzák, hogy megakadályozzák. Miután lemennek a csapóajtón, a három gyerek kiállja a próbatételeket, majd Harry egyedül találkozik egy másik tanárral, a dadogó Mógussal, akiről kiderül, hogy Voldemort-t szolgálja és az az ő testében lakozik. Mivel Mógus nem bírja Harry érintését, a fiú ezzel a fegyverrel súlyosan meg is sebesíti őt és megakadályozza Voldemort-t a kő megszerzésében. Harry a gyengélkedőben ébred, ahol Dumbledore professzor, az iskolaigazgató, elmagyarázza neki az eseményeket.</p>

            <h1>Harry Potter és a Titkok Kamrája</h1>
            <p>Harry második tanévében szörnyű merényletek zajlanak a Roxfortban. Kiderül, hogy újra kinyílt a legendás Titkok Kamrája, és az ott lakó szörnyeteg(a baziliszkusz) fenyegeti a diákokat. Harry egy különös, ötvenéves napló segítségével megismerkedik Tom Denemmel, akiről utóbb kiderül, hogy nem más, mint a hajdani Voldemort, tizenhat éves korában. A régi lánymosdóban találkoznak Hisztis Myrtle-lel, a kísértettel, akit a Titkok Kamrájában rejtőző szörnyeteg ölt meg pontosan ötven évvel korábban. Ugyancsak a régi lánymosdóban találják meg a Titkok Kamrájának bejáratát. Harry megküzd a múltbeli Voldemorttal, legyőzi a baziliszkuszt és megmenti Ginny Weasley-t.

            A Harry Potter és a Titkok Kamrája (Harry Potter and the Chamber of Secrets) 1998. július 2-án jelent meg angolul. A könyvnek a hatodik könyvvel van fontos tematikus kapcsolata. (Az említett kötetben fontos szerepet játszik Voldemort (Tom Denem) gyermekkora, valamint a napló, Voldemort egyik horcruxa.)</p>


            <h1>Harry Potter és az azkabani fogoly</h1>
            <p>Harry megtudja, hogy Sirius Black, egy körözött tömeggyilkos megszökött Azkabanból, a varázslók börtönéből. Black ellen az egész varázsvilágban körözés zajlik, mert köztudott, hogy meg akarja ölni Harryt, mint ahogy az is, hogy annak idején ő árulta el Harry szüleit Voldemortnak. Végül Harry és barátai számára kiderül, hogy nem Sirius Black – aki egyébként Harry keresztapja – a bűnös, hanem egy Peter Pettigrew nevű varázsló, aki patkány képében évek óta Ron (és a Weasley család) háziállata. Harryék megmentik Siriust az elfogatástól, Pettigrew azonban megszökik. Harry ebben a részben nem találkozik Voldemorttal, megismerkedik azonban a dementorokkal, a földkerekség legocsmányabb élőlényeivel, és megtanul védekezni ellenük. Ez az egyetlen könyv a sorozatban, amelyben nem jelenik meg Voldemort. Karácsonykor Sirius elküldi Harrynek a leggyorsabb versenyseprűt, a Tűzvillámot. Harry Potter és az azkabani fogoly (Harry Potter and the prisoner of Azkaban) angol nyelven 1999. július 8-án tették közzé. Ez a könyv elnyerte, többek között, a Costa-díjat és a Bram Stoker-díjat, mint az egyik legsikeresebb fantasy könyv az elmúlt években.</p>


            <h1>Harry Potter és a Tűz Serlege</h1>
            <p>A Roxfortban megrendezik a Trimágus Tusát, amelyen három varázslóiskola bajnokai mérik össze tudásukat.A Tűz Serlege kiválaszt mindegyik varázslóiskolából egy 17. életévét betöltött diákot, aki bedobja nevét a Serlegbe. Azonban valaki titokzatos módon benevezi Harryt is, így ő lesz a negyedik bajnok.

            A fiúnak megtetszik Cho Chang, az ötödéves, hollóhátas lány. Harry megkérte, hogy legyen a párja a Karácsonyi Bálon, de Cho visszautasítja a kérést, azt mondja, Cedric felkérte őt, és elfogadta. A fiúnak végül Padma Patil, az egyik évfolyam társa lesz a partnere.

            Harry rengeteget tanul az év során, hogy helytálljon a kemény próbák során. A harmadik – utolsó – próba csapdának bizonyul: Harry és roxfortos bajnoktársa, Cedric Diggory egy temetőbe kerülnek, ahol Voldemort és Peter Pettigrew várják őket. Cedricet meggyilkolják. Ahogy később kiderül az áruló az áll Mordon professzor volt aki igaziból egy halálfaló, csak a százfűlé főzettel más alakot öltött. Voldemort, bonyolult feketemágiát alkalmazva, amelynek során felhasználja Harry vérét is, újra testet ölt. Harry megmenekül, és a Roxfortban beszámol Voldemort visszatéréséről. Dumbledore feltétel nélkül hisz neki, azonban Cornelius Caramel, a mágiaügyi miniszter, hatalmát féltve inkább ragaszkodik a társadalom biztonságának látszatához, és önmagát is meggyőzi, hogy Harry hazudik...</p>


            <h1>Harry Potter és a Főnix Rendje</h1>
            <p>A hatalmát visszanyert Voldemort nem lép színre nyíltan, a Mágiaügyi Minisztérium pedig lejárató kampányt folytat Harry és Dumbledore ellen. A miniszter a Roxfortba küldi tanárnak, majd főinspektornak a szadista hajlamú boszorkányt, Dolores Umbridge-et, aki noha elvileg sötét varázslatok kivédését tanít, valójában megakadályozza, hogy a gyerekek gyakorlati önvédelmet tanuljanak, mert Caramel attól fél, hogy Dumbledore megtámadja a minisztériumot. Harry és társai ezért Dumbledore Serege néven titkos önvédelmi szakkört szerveznek. Harrynek mindeközben visszatérő álma van egy sötét folyosóról, míg végül kiderül, hogy – a hajdani, meghiúsult gyilkos átok következtében – Voldemorttal kölcsönösen belelátnak egymás fejébe. Amikor Voldemort erről tudomást szerez, csapdába csalja Harryt, és a kaland – amelynek végeztével a minisztérium is kénytelen elismerni, hogy a Sötét Nagyúr visszatért – Sirius Black életébe kerül. Harry megtudja, hogy Voldemort hajdan egy jóslat miatt tört az életére, mert úgy vélte, Harry az egyetlen, aki elpusztíthatja őt. Harry kénytelen szembenézni a ténnyel, hogy a sors akarata szerint végül vagy ő fogja megölni Voldemortot, vagy Voldemort őt.</p>


            <h1>Harry Potter és a Félvér Herceg</h1>
            <p>Dumbledore közli Harryvel, hogy ebben az évben különórákat szeretne tartani neki. Az órák során régi emlékekbe tekintenek be, és Harry képet alkot Voldemort múltjáról. Megtudja, hogy a Sötét Nagyúr hétfelé szakította lelkét: hat horcruxot készített, hogy így nyerje el a halhatatlanságot. Voldemort tehát mindaddig elpusztíthatatlan, amíg az összes horcruxát meg nem semmisítették. Harry eközben – aki a titokzatos „Félvér Herceg” régi tankönyvének segítségével zseniális bájitalfőzővé válik – gyanakodni kezd, hogy Draco Malfoy valójában halálfaló, és Piton segít neki titkos célja elérésében. Dumbledore ismételten leszögezi, hogy feltétel nélkül megbízik Pitonban. Végül kiderül, hogy Malfoy terve – Voldemort parancsára – Dumbledore megölése volt. Malfoy azonban képtelen elkövetni a gyilkosságot, így Piton – számos halálfaló, valamint a láthatatlanul jelen levő Harry szeme láttára – a gyilkos átokkal megöli Dumbledore-t. A gyilkosságot követő csatában Harry számára kiderül, hogy valójában Piton a Félvér Herceg. Harry elhatározza, hogy utolsó évére nem tér vissza a Roxfortba, hanem teljesíti a Dumbledore-tól ráhagyott küldetést: felkutatja és elpusztítja a horcruxokat, és ha sikerül, bosszút áll Pitonon is.</p>

            <h1>Harry Potter és a Halál ereklyéi</h1>

            <p>Harry, Ron és Hermione izgalmas és megrendítő kalandok során bukkannak a horcruxok nyomára. Az események egy csatában végződnek, amelyre a Roxfortban kerül sor. Harry a Voldemort által meggyilkolt Piton emlékeiben elmerülve megtudja, hogy Piton kezdettől fogva mély érzelmeket táplált édesanyja, Lily Evans iránt. Kiderül számára az is, hogy Piton Dumbledore kérésére végzett az igazgatóval, aki egy mágikus baleset (az egyik horcrux elpusztítása) miatt már amúgy is a halálán volt. Az is kiderül, hogy valójában ő, Harry is egy horcrux, amelyet Voldemort tudtán és akaratán kívül készített: amikor annak idején visszaszállt Voldemortra a gyilkos átok, a Sötét Nagyúr amúgy is szakadozott lelkéből lehasadt egy rész, és hozzákapcsolódott a szobában lévő egyetlen élőlény – Harry – lelkéhez. Így Voldemort mindaddig elpusztíthatatlan, amíg Harry életben van. Harry úgy dönt, hogy önként életét adja barátaiért, és védekezés nélkül áll Voldemort elé. Ezzel az elhatározásával méltó tulajdonosa lesz három mágikus tárgynak, a Halál ereklyéinek, s a legenda úgy szól, hogy aki az ereklyéket egyesíti, az a halál urává válik. Voldemort ismételten kimondja Harryre a gyilkos átkot, az azonban nem Harryt pusztítja el, hanem a testében élő lélekrésszel végez. Mivel ugyanis korábban Voldemort Harry vérét használta fel, hogy testet öltsön, Lily áldozata nemcsak Harry, hanem Voldemort saját vérében is továbbélt. E varázs következtében Harry nem hal meg, hanem egy köztes állapotba kerül, ahol választhat élet és halál között. A visszatérést választja, s a végső összecsapásban Voldemort még egyszer, utoljára megpróbálja megölni őt, azonban az átok ismét visszapattan, és – az immár horcruxok nélküli – Voldemort meghal.

            A tizenkilenc évvel később játszódó epilógusból megtudjuk, hogy Harrynek Ginny Weasleytől három gyermeke született, és Ron is összeházasodott Hermionéval. Harry az egyik fiának az Albus Perselus nevet adta. Másik két gyermekük keresztneve: Lily (Harry édesanyja után) és James Sirius (Harry édesapja, valamint Harry keresztapja, Sirius Black után). Ronnak és Hermionénak két gyermeke van: Hugo és Rose.</p>



        </div>
    )
}